<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>
</head>

<body>
  <script>
    const result = fetch("https://mdn.github.io/learning-area/javascript/oojs/json/superheroes.json").then((response) => {
      console.log(response)
      // response.ok 를 이용한 예외처리
      if (!response.ok) {
        throw new Error(`HTTP ERROR!! State: ${response.status}`);
      }
      return response.json()
    })
      .then((data) => {
        console.log(data)
        return data;
      }).catch((error) => {
        console.error(error)
      })

    console.log(result)

    // fetch 는 HTTP 응답 코드가 404나 500과 같은 '실패' 상태여도 resolve 상태의 프로미스를 반환합니다. 개발자가 의도한 데이터를 받지 못했지만, 서버와의 통신 자체는 성공했기 때문에 약속이 이행됐다고 판단하기 때문입니다. 
  </script>

</body>

</html>